baseurl = "/"
title = "Daniel Brodsky"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

disqusShortname = "danbrodsky"
googleAnalytics = "UA-186824116-1"

pygmentscodefences = true
pygmentsuseclasses = true

[params]
    author = "Daniel Brodsky"
    description = "personal site for blog and CTF writeups"
    keywords = "blog,developer,personal, CTF, writeup"
    info = "Software Engineer"
    avatarurl = "images/avatar.jpg"
    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/danbrodsky/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 3
    url = "mailto:danbrodsky@pm.me"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/danbrodsky/"
[[params.social]]
    name = "Resume"
    icon = "fas fa-file"
    weight = 4
    url = "https://www.danbrodsky.me/resume.pdf"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "CTF Writeups"
        weight = 3
        url = "/writeups/"

[module]
  [[module.mounts]]
    source = "webrtl"
    target = "static/divein/"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "content"
    target = "content"

